### ISSUE TITLE
i18n - Cache invalidation when multiple clients with different languages

### ISSUE THREAD

**Issue by PEM--** [ssr-server/ssr#10]
Currently, when multiple clients hits the server, each client's language will trigger a cache invalidation, re-render the app and set the HTML for the last received language.

HTML caching should be done for each language as the current implementation defeat the caching purpose making it non effective for i18n.

@blntylmn Could you reproduce the same caching behavior that has been created for `platform`? It implements a "per platform" cache. Hence, cached pages for desktops (`default`) isn't invalidated when an iPhone (`iphone`) hits the server.

**Comment by blntylmn** [comment]
This issue should gone after we switching i18n with react-intl.

**Comment by timothyarmes** [comment]
The userLanguage just needs to be included in the cache key, something like:

${platform}-${userLanguage}-${url}

**Comment by blntylmn** [comment]
Implemented. The issue should gone now..
