### ISSUE TITLE
How would I get the hostname?

### ISSUE THREAD

**Issue by j-jackson** [ssr-server/ssr#17]
Thanks for this fantastic package! I'm surprised I haven't heard more about it.

My application uses the subdomain to subscribe to all the sites data and I'm having trouble working out how I can do this with SSR.

My current non SSR version uses blaze & flowrouter so I can just use `window.location.hostname` on the client or `this.connection.httpHeaders.host` on the server, but I'm not sure how to set this up to so it works on both.

**Comment by cbilotta** [comment]
Hello,

Not sure I understood properly but, you can probably use Meteor.absoluteUrl()

Here's the link to the doc : https://docs.meteor.com/api/core.html#Meteor-absoluteUrl

Hope it helps !

**Comment by j-jackson** [comment]
@iRayzer thanks for the reply. 

Unfortunately I don't think `Meteor.absoluteUrl()` includes subdomains.

Using the [PubSub](https://github.com/ssrwpo/ssr/blob/master/demo/imports/routes/PubSub.jsx) route in the demo app as an example, lets say the generated users included a username field and I wanted to subscribe to just one user via `http://johndoe.localhost:3000/pubsub`

```javascript

  const username = howdoIGetUsernameFromHostname?

  dispatch => ({
    handleSubscribe: createHandleSubscribe(
      dispatch,
      PubSubPublicationName,
      PubSubCol.find(username), <<-
      'isPubSubSubscribed',
      'PubSub',
    ),
```

Normally you could just use `window.location.hostname` but obviously this wont work on the server and then something like `this.connection.httpHeaders.host` wont work on the client.

This seems like it should be a very simple thing to do so I'm probably just missing something!

I'm new to redux but is there a way I could add the user information to the redux store when the page loads and then just read the username from the store rather then in the component like above?

**Comment by PEM--** [comment]
This sounds not related to an issue and more related to a usage question. I'm closing this.

**Comment by PEM--** [comment]
@j-jackson, the rule of thumb here is: SSR is for public payloads. Do not use the server to subscribe to user's data for delivering public HTML payload. How Google could parse this page? Subscribe to your data only once the payload is delivered and patch your redux store with the results.

**Comment by PEM--** [comment]
@j-jackson By the way, this package could be even more publicized if you put a star on it 😉  When there will be enough stars, I'm sure that some of our early stargazers with very well known Youtube channel will surely do some interesting tutorial videos on the subject you are in 😄
