### ISSUE TITLE
We should considering about Apollo/GraphQL

### ISSUE THREAD

**Issue by blntylmn** [ssr-server/ssr#3]
Actually I was thinking about to convert my project which includes apollo graphQL, i18next, redux, universal rendering , mongoDB, restAPI etc. They were running on two separated project. One for graphQL and one for the app (on classic nodeJS and express). Then I found your repo and thought that **"this is it"**.
In my opinion **Apollo + graphQL** has huge benefits and should be in this boilerplate too.

**Comment by PEM--** [comment]
For the moment, I don't have any customer that requires GraphQL or Falcor. I think the same goes for @iRayzer. At the beginning, I was thinking of using Grapher, which surely ressembles a lot to Falcor, to lighten the burden of injecting specific data for specific routes. Still, it wasn't that mandatory for a first release.

There should be something to do about it in the next major release. The gotcha will be to ensure that server side caching will not increase the memory cost too much. GraphQL, Falcor or Grapher could help achieve it.

**Comment by PEM--** [comment]
By the way, if you want to hop in the bandwagon and try to start the v2, we could add you to the organization and you could start digging on the V2. What do you think?

**Comment by blntylmn** [comment]
I need all of them above listed and maybe more. (animations,  localstorage  etc.) Maybe we can go another branches (or not) for custom needs if you want to keep the master one simple.
**That would be nice if I could helpful**.

**Comment by PEM--** [comment]
Nice, nice, nice. I will setup the repo for adding a branching model. Certainly git-flow to ease our merges.

**Comment by blntylmn** [comment]
Btw this will be my first contribition so I need you lead me sometimes how to do things ;)

**Comment by PEM--** [comment]
Done, I've added you as an owner of the organization. Welcome!

So from now on, we will be using [git-flow](http://danielkummer.github.io/git-flow-cheatsheet/).

Just create you own `grahpql` feature branch from the `develop` one and you're ready to go.

We can start a chat with Google Hangouts. My account is equivalent to my email (see my Github profile page). It will be easier than filling up this issue with posts.

**Comment by blntylmn** [comment]
Ok thanks. I accepted. I'm outside now. I will investigate the git-flow and create a hangouts account asap. Probably tomorrow. See you..

**Comment by PEM--** [comment]
In the roadmap. Just closing this to keep our repo clean 😉
