### ISSUE TITLE
Does this have server-side autologin?

### ISSUE THREAD

**Issue by mariusglauer** [ssr-server/ssr#32]
Very nice package! I am using FlowRouter SSR right now which has the ability to render Meteor.user() on the server-side by looking at the login token which is stored inside a cookie. Can this package do this, too? I found nothing in your docs and in the code.

**Comment by PEM--** [comment]
Hi @gbhrdt. Actually, we consider server side authentication has a bad practice for SSR. Meteor relies on pub/sub mechanism for authentication. Though it's completely transparent, the Meteor's autologin process is achieved only once Meteor has started on the client.

We prefer favoring patterns based on asymetric behavior on the server and the client thanks to our `asymetricSsr` HOC. Once autologin has started, you're then free to update client's data (or delay it to avoid loads on the server) and patch the reducers with the diffs of data that rely on logged-in sessions. This measure avoids unnecessary RAM usage on the server and prevents replay attacks that plague cookie based auth mechanisms.

**Comment by cbilotta** [comment]
Hello,No it does not have it, we think it is bad practice for security reasons.However Meteor actually automatically connects you once the DDP connection is established.So you can just wait for it and automatically "refresh" the page.Le 25 févr. 2017 12:08, Marius <notifications@github.com> a écrit :Very nice package! I am using FlowRouter SSR right now which has the ability to render Meteor.user() on the server-side by looking at the login token which is stored inside a cookie. Can this package do this, too? I found nothing in your docs and in the code.

**Comment by mariusglauer** [comment]
Thanks for your clarification, that makes much sense. Never thought of the security and performance issues regarding server side auth.
