### ISSUE TITLE
Remove demo folder from meteor package

### ISSUE THREAD

**Issue by mariusglauer** [ssr-server/ssr#35]
Would it be possible to remove the `demo` folder from the meteor package? Because of the demo's `package.json`, meteor tries to include the `bcrypt` library in the server bundle, which I am currently experiencing deployment issues with.

**Comment by PEM--** [comment]
Humm... disgusting behavior. I'll work on it.

**Comment by PEM--** [comment]
@gbhrdt Should be good with the freshly published 2.1.5.

**Comment by mariusglauer** [comment]
Works like a charm. Thank you very much!
