### ISSUE TITLE
Document Windows compiling issue on the demo: Unexpected token error

### ISSUE THREAD

**Issue by julian-rare** [ssr-server/ssr#37]
While running on windows:

![image](https://cloud.githubusercontent.com/assets/17118369/23493375/759875ee-ff5f-11e6-8106-3ee52a6bd982.png)

**Comment by PEM--** [comment]
Hi @julian-rare. Looks like an issue at the Babel level. Can you tell me more on this?

**Comment by julian-rare** [comment]
I'm running the demo, no changes to it, npm runs ok, but once I call meteor I get this error, doesn't give me a lot of detail on whats wrong.

Try to run in on a PC and let me know if it works

**Comment by PEM--** [comment]
I don't own any Windows and I'm quite sure that none of our contributors owns one too. Are you familiar enough to adapt the demo to be compliant with this environment?

**Comment by julian-rare** [comment]
well packages should be OS agnostic (like vanilla meteor), don't know why the OS should be an issue, the ssr package I'm using works perfect on my PC but I'm trying to replace it with this one.

**Comment by PEM--** [comment]
You're issue is related to the demo. Not the package itself. The demo is... well... a demo. Having contributions for making it working on this OS would be neat.

Just one thing, if you want to contribute on the demo, be sure to use the `develop` branch.

**Comment by julian-rare** [comment]
I'm trying but failed to solve this issue, so came here for help

**Comment by PEM--** [comment]
I'm really unfamiliar with this OS 🤔  I would proceed step by step and create my own test project. As it's Babel related, I would stick on Meteor's default which are quite nice. The one used in the demo is targeted for production performances mainly for Unix based environment.

**Comment by julian-rare** [comment]
that's an option, but a demo should be done for everybody to use, can you pinpoint the parts that are unix specific so I can change them, looking at the source code haven't managed to find.

**Comment by PEM--** [comment]
I was googling around on Babel issues on Windows. Indeed, there are some serious ones. A lot of them are related to JSX. Try to remove the `.babelrc` in the demo, I'm not sure of it, but, Meteor could have implemented stuff to circumvent this.

**Comment by PEM--** [comment]
There are also some serious ones on CSS imports. Really weird. The import rules could be a problem. Try to remove `postcss` usage: https://github.com/ssrwpo/ssr/blob/master/demo/.meteor/packages#L15

EDIT : Remove also this the `client/styles` directory as it doesn't add any value for toying with our example and may interfere into running it.

**Comment by julian-rare** [comment]
Will do, thank you! will post back my results

**Comment by julian-rare** [comment]
Hope this is an improvement, this is what I get after I removed the .babelrc

![image](https://cloud.githubusercontent.com/assets/17118369/23495906/4bfad2a8-ff6f-11e6-8a0b-36c5673aaf78.png)

**Comment by PEM--** [comment]
Sounds better. Babel isn't stopped anymore on JSX interpretation. So, according to Babel's error message I see, it seems that only the `babel-plugin-transform-class-properties` is necessary. This transformer allows to use autobinded methods on a `class`.

You will need to create your own `.babelrc` using just this:
```
{
  "presets": ["meteor"],
  "plugins": [
    "transform-class-properties"
  ]
}
```

**Comment by julian-rare** [comment]
That did the trick, is working now PEM, thank you!

**Comment by PEM--** [comment]
Yeah! Super nice. I'll let this issue open so that we can update the docs to better inform Windows's users. Thanks for you investigations 👍

**Comment by julian-rare** [comment]
Will have to clone the repo again and start by doing the change on the .babelrc and see if it will work

**Comment by PEM--** [comment]
Indeed, the styles may work and making them removed for Windows's users would not be nice. I've used Stylus and PostCSS. The only weirdness could be this line: https://github.com/ssrwpo/ssr/blob/master/demo/client/styles/common.styl#L1

It's using a path and Windows is using its own way of expressing path.

**Comment by julian-rare** [comment]
Did  a new pull and now it works just by replacing the .babelrc code from

`../.babelrc`

to 

```
{
  "presets": ["es2015", "meteor"],
  "plugins": [
    "transform-class-properties",
    "transform-react-constant-elements",
    "transform-react-inline-elements",
    "transform-inline-environment-variables",
    "transform-dead-code-elimination"
  ]
}
```


the babel compiler freaks out by not seeing a json, but a relative path.

I still get the css warning, but the styles are working ok
![image](https://cloud.githubusercontent.com/assets/17118369/23533368/7ccd4a14-0005-11e7-9676-d789b0aba015.png)
