### ISSUE TITLE
i18next-express-middleware

### ISSUE THREAD

**Issue by j-jackson** [ssr-server/ssr#39]
The [faq](i18n) says that i18n is optional, but I get `Error: Can't find npm module 'i18next-express-middleware'.` on a fresh install.

This is what I have installed

```
meteor create demo

meteor yarn add react react-dom react-router-dom@next express helmet \ 
    react-helmet winston logatim receptacle useragent redux react-redux moment \ 
    serialize-javascript lodash actual is-retina

meteor add ssrwpo:ssr
```

**Comment by PEM--** [comment]
It's says that it's usage is optional but the dependencies are required.

**Comment by Morganjackson** [comment]
Where does it say the dependencies are required?

**Comment by PEM--** [comment]
https://github.com/ssrwpo/ssr/blob/master/README.md#installation-in-your-own-project

**Comment by PEM--** [comment]
@j-jackson, @Morganjackson, Guys, Github's issues are not a forum. We rely on it for real issues as well as our roadmap management. We can create a dedicated thread on Meteor's forum. That would be much nicer and users could then use already answered questions and share their best practices.
