### ISSUE TITLE
does this support cordova hot code push?

### ISSUE THREAD

**Issue by sirpy** [ssr-server/ssr#43]
hot code is dependant on serving assets from http://meteorserver/__cordova/
where would requests to /__cordova go?
is it possible to direct them to the default meteor handler?
Thanks

**Comment by PEM--** [comment]
Indeed, I think that those request may be interpreted by Express and RRv4. We could avoid interpreting them by enhancing the following RegExp: https://github.com/ssrwpo/ssr/blob/master/src/server/createRouter.js#L33

**Comment by PEM--** [comment]
@sirpy What kinds of assets are requested by Cordova? If they contain a `.`, the aforementioned should let them delivered by Meteor's server.

**Comment by sirpy** [comment]
its the hot code push assets, so it can be anything, but mostly javascript files

**Comment by PEM--** [comment]
I will prepare a release with this RegExp: `/^\/(?!api\/)(?!__cordova\/)[^.]*$/` to be sure that these URLs are handled via Meteor and not Express.

**Comment by PEM--** [comment]
Should be good with 2.4.0.

**Comment by sirpy** [comment]
As a sidenote what i modified in the meteor-react-router-ssr is that by default all routes are not handled by the ssr server only routes that are defined. i think this is a better solution than simply excluding just __cordova, since there might be other packages that want to handle some routes on a lower level and other system routes.
