### ISSUE TITLE
TypeError: rewind is not a function

### ISSUE THREAD

**Issue by stolinski** [ssr-server/ssr#51]
I'm having a hard time getting this going on an extremely simple example.  Not sure what's going on here. I'm just trying to render 1 single component and am getting this error.

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

Logging the Component after import shows that it's def not undefined and type of function.

Repo is here:
https://github.com/stolinski/ST2015

**Comment by stolinski** [comment]
I found an error in my import however now I'm getting an odd error instead. 

```
TypeError: rewind is not a function
W20170430-21:01:29.606(-6)? (STDERR)     at applicationRendering (packages/ssrwpo:ssr/server/steps/applicationRendering.jsx:37:18)
```

**Comment by cbilotta** [comment]
Hello, 
I launched your app,
Turns out you need to downgrade react-helmet from 5.0.0 to 4.0.0. 
Not sure why. I'll dig into it, but it will fix your problem for now :)
By the way, if you plan on doing per-route data loading, you should probably use the develop branch.

**Comment by PEM--** [comment]
Hi guys,

@stolinski, Sounds like you haven't updated your packages: https://github.com/stolinski/ST2015/blob/master/.meteor/versions#L64

`react-helmet` has changed its API. Any of our release after the 2.3.0 should comply with these changes: https://github.com/ssrwpo/ssr/blob/master/CHANGELOG.md#230-react-helmet-5x-sitemapjs--humanstxt

**Comment by stolinski** [comment]
@PEM-- Odd, I installed with the meteor add command just 2 days ago and would have expected it to grab the latest.

Updated everything full and it's working fine.

**Comment by PEM--** [comment]
Yeah 👍
