### ISSUE TITLE
[ Help Wanted ] Understanding syncActionsFromStore

### ISSUE THREAD

**Issue by Aetherall** [ssr-server/ssr#58]
Hi,
This project seems to have a huge potential which I want to use, but I'm experiencing few difficulties to understand the syncActionsFromStore function ...

Why does the function doesn't handle the new items in the fromRemote array?

I tried to run it with 3 items in collectionStore and 5 in fromRemote and the dispatchActions array was still empty.. is it the expected behaviour?

Thanks !

Edit : I figured out by myself

**Comment by PEM--** [comment]
There's an example of its usage in the demo.
