### ISSUE TITLE
cacheConfig - How to disable route level caching

### ISSUE THREAD

**Issue by s7dhansh** [ssr-server/ssr#60]
I tried the following code but it is still caching the route.
```
  static ssr = {
    cacheConfig: {
      enable: false,
    },
  }
```
It stops caching only when I disable caching in server/routes by:
```
options: {
		enableCaching: false,
	}
```

I am using `develop` branch.
Is this the desired behavior? How to enable/disable caching w.r.t specific routes?

**Comment by PEM--** [comment]
As stated in the contribution guide, we don't take usage questions. We want to keep this repo as clean as possible. I'm closing this.

BTW, cache options are handled within `src/server/steps/cacheFilling.js`. We are not quite sure to keep it the way it's implemented right now. Though static analysis is nice and simple, this triggers overhead while parsing the app.
