### ISSUE TITLE
'resetSSRCache' is in the docs, but not in the package

### ISSUE THREAD

**Issue by mcissel** [ssr-server/ssr#63]
Is there another way to reset the cache?

**Comment by PEM--** [comment]
The only docs for the production package is our README.md. @timothyarmes and I have started some writings on our next release, the 3.X. For the moment, it's far from being finished.

**Comment by PEM--** [comment]
By the way, modifying any collections used in the serialization resets the cache. The rest of the API is not exposed at the moment.
