### ISSUE TITLE
Q: Do I need moment and lodash?

### ISSUE THREAD

**Issue by s7dhansh** [ssr-server/ssr#67]
They are peer dependencies, and removing them does not seem to give any obvious error. Hence I was wondering, if they are required for this package to work properly?

**Comment by cbilotta** [comment]
I will check on that briefly!

**Comment by cbilotta** [comment]
We do use lodash.
However, I didn't see any use of moment in the develop branch.
Maybe you can make a pull request ?
Thanks!

**Comment by s7dhansh** [comment]
https://github.com/ssrwpo/ssr/pull/71

moment is only used in `demo`. `lodash` is also used only in a couple of shared functions `createHandleSubscribe` and `createHandleSyncViaMethod`. I am not getting any error as I am not using these two.
I think we can skip lodash as well, to reduce the bundle. Or use `lodash.debounce` and `lodash.omit`.

**Comment by cbilotta** [comment]
Lodash is used by the package in createRouter
