### ISSUE TITLE
nested asymetricSsr

### ISSUE THREAD

**Issue by sakulstra** [ssr-server/ssr#73]
Not sure if this is a real bug as it doesn't make a lot of sense to nest `asymetricSsr` components below each other. Anyways I tried to and it caused some errors as the nested component may get unmounted before requestAnimationFrame is fired which results in :
```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the _class component.
```

```
componentDidMount() {
      requestAnimationFrame(() =>
        // component may be already unmounted now
        this.setState({ mounted: true }),
      );
    }
```

**Comment by PEM--** [comment]
Indeed, nesting `asymetricSsr` is really not a good idea. I don't see how we could introspect the provided component and warn the user about his mistake. Event if it was feasible, a complex hierarchy of components couldn't be analyzed without deep and costly analysis. And I'm not even touching composition...

Well, nothing to be done here, but thanks for the info.

**Comment by cbilotta** [comment]
Actually I also have this problem even with no nested asymetricSsr :/
