### ISSUE TITLE
AssertionError: Cannot await without a Fiber

### ISSUE THREAD

**Issue by mcissel** [ssr-server/ssr#76]
after updating to Meteor 1.5.1, the SSRWPO:SSR package doesn't work, it throws the error: `AssertionError: Cannot await without a Fiber`, bringing attention to these lines of code:
```
 at applicationRendering (packages/ssrwpo:ssr/server/steps/applicationRendering.jsx:62:40)
 at packages/ssrwpo:ssr/server/createRouter.js:109:5
```

this was tested using the demo in the github repo here

**Comment by mitkodkn** [comment]
Experiencing the same error after updating to Meteor 1.5.1.

**Comment by cbilotta** [comment]
Hello, develop or master ?

**Comment by mcissel** [comment]
@iRayzer, It does *not* happen on develop.

I just tested it on develop. I cloned the project, ran
`git clone https://github.com/ssrwpo/ssr.git`
`cd ssr/demo`
`git checkout develop`
`meteor update`
`meteor yarn install`
~`meteor`~
`meteor yarn start`

The fiber error is not there, and the demo loads fine (albeit a PropTypes dep. warning)

**Comment by cbilotta** [comment]
Hello, I fixed it.
Unfortunately I will have to wait on @PEM-- to publish a release on atmosphere.
But, you can just clone the master branch into your packages folder for the time being :)

Have a great day!

**Comment by mcissel** [comment]
@iRayzer I checked out master, and ran
`git clone https://github.com/ssrwpo/ssr.git`
`cd ssr/demo`
`meteor update`
`meteor yarn install`
`meteor`

but when I open the application, I see the error:
```
ReferenceError: Fiber is not defined
   at packages/ssrwpo:ssr/server/createRouter.js:118:9
```

**Comment by mcissel** [comment]
@iRayzer  I haven't been able to find a solution for this yet. Any update?
